"""
loco-mujoco demo: single-episode rollout against a plain RL env.

Purpose
-------
Runs ONE episode on the benchmark's `RLFactory.make(...)` env with random
actions (the default) or with a checkpointed policy (if `--checkpoint_path`
and `--algo` are supplied). Prints per-step reward and termination flags,
then exits. This is the "show me one run" sibling of `run_eval.py` —
there is no dataset, no success-rate aggregation, no training.

loco-mujoco has no WebSocket policy-server protocol (see skill case study,
"loco-mujoco edge case"), so this script does NOT take `--policy_server_addr`.
For RL benchmarks that do ship a policy-server, use the IL-flavour `run_demo.py`.

Every invocation creates `<log_dir>/demo/<env>--<YYYYMMDD_HHMMSS>/` that
contains `demo.log` mirroring stdout and (opt-in) a `demo.mp4` recording.

Example
-------
    # Random-action demo on UnitreeH1 for 50 steps
    python scripts/run_demo.py --env_name UnitreeH1 --n-steps 50

    # Replay a checkpoint deterministically
    python scripts/run_demo.py --checkpoint_path outputs/.../PPOJax_saved.pkl \\
        --algo ppo --env_name UnitreeH1 --n-steps 200 --deterministic

    # Inspect the per-run directory afterwards
    ls logs/demo/UnitreeH1--*/

Generated by benchmark-env-generator (RL Category, dispatcher mode).
"""
import argparse
import atexit
import os
import signal
import sys
from datetime import datetime
from typing import Optional

import numpy as np


ALGO_CLASS_MAP_STR = {
    "ppo": ("loco_mujoco.algorithms", "PPOJax"),
    "gail": ("loco_mujoco.algorithms", "GAILJax"),
    "amp": ("loco_mujoco.algorithms", "AMPJax"),
    "rl_mimic": ("loco_mujoco.algorithms", "PPOJax"),
}


def log(msg: str, log_file: Optional["os.PathLike"] = None) -> None:
    """Print to stdout and, if open, also write to a log file (flushed each call)."""
    print(msg)
    if log_file is not None and not log_file.closed:
        log_file.write(msg + "\n")
        log_file.flush()


def _load_algo(algo_name: str):
    mod_name, cls_name = ALGO_CLASS_MAP_STR[algo_name]
    mod = __import__(mod_name, fromlist=[cls_name])
    return getattr(mod, cls_name)


def main():
    parser = argparse.ArgumentParser(
        description="Single-episode demo rollout on a loco-mujoco RL env.")
    parser.add_argument("--env_name", type=str, default="UnitreeH1",
                        help="Robot env name (default: UnitreeH1). See benchmark.md for the full list.")
    parser.add_argument("--task_factory", type=str, default="RLFactory",
                        choices=["RLFactory", "ImitationFactory"],
                        help="RLFactory is pure RL (no dataset); ImitationFactory pulls mocap datasets.")
    parser.add_argument("--n-steps", type=int, default=50,
                        help="Max steps for the single episode (default 50).")
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--checkpoint_path", type=str, default=None,
                        help="Optional: replay a saved checkpoint instead of random actions.")
    parser.add_argument("--algo", default="ppo", choices=list(ALGO_CLASS_MAP_STR.keys()),
                        help="Algorithm class if --checkpoint_path is set.")
    parser.add_argument("--deterministic", action="store_true",
                        help="If --checkpoint_path is set, use deterministic policy (log_std=-inf).")
    parser.add_argument("--use_mujoco", action="store_true",
                        help="Run on CPU MuJoCo instead of MJX (checkpoint replay only).")
    parser.add_argument("--gui", action="store_true",
                        help="Call env.render() each step (X11 compose profile only).")
    parser.add_argument("--log_dir", type=str, default="./logs",
                        help="Parent dir for per-run demo outputs (created if missing).")
    parser.add_argument("--save_video", action="store_true",
                        help="Record an MP4 under the per-run dir. Needs an offscreen GL "
                             "context on headless containers (loco-mujoco: MUJOCO_GL=egl works).")
    parser.add_argument("--video_fps", type=int, default=30)
    args = parser.parse_args()

    os.environ.setdefault("XLA_FLAGS", "--xla_gpu_triton_gemm_any=True")

    date_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    run_dir = os.path.join(args.log_dir, "demo", f"{args.env_name}--{date_str}")
    os.makedirs(run_dir, exist_ok=True)
    log_path = os.path.join(run_dir, "demo.log")
    log_file = open(log_path, "w")

    def _cleanup(signum=None, frame=None):
        try:
            if not log_file.closed:
                log_file.close()
        finally:
            sys.stdout.flush()
            sys.stderr.flush()
        if signum is not None:
            os._exit(1)

    signal.signal(signal.SIGINT, _cleanup)
    signal.signal(signal.SIGTERM, _cleanup)
    atexit.register(lambda: None if log_file.closed else log_file.close())

    log("=" * 60, log_file)
    log("loco-mujoco demo", log_file)
    log("=" * 60, log_file)
    for k, v in sorted(vars(args).items()):
        log(f"  {k}: {v}", log_file)
    log(f"  run_dir: {run_dir}", log_file)
    log("=" * 60, log_file)
    log("", log_file)

    # Checkpoint replay path — delegate to the algorithm's own play_policy.
    if args.checkpoint_path is not None:
        from omegaconf import OmegaConf
        from loco_mujoco import TaskFactory

        algo_cls = _load_algo(args.algo)
        agent_conf, agent_state = algo_cls.load_agent(args.checkpoint_path)
        config = agent_conf.config

        factory = TaskFactory.get_factory_cls(config.experiment.task_factory.name)
        OmegaConf.set_struct(config, False)
        config.experiment.env_params["headless"] = True
        env = factory.make(**config.experiment.env_params,
                           **config.experiment.task_factory.params)

        log(f"replaying checkpoint={args.checkpoint_path} "
            f"algo={args.algo} deterministic={args.deterministic}", log_file)
        play_kwargs = dict(deterministic=args.deterministic, n_steps=args.n_steps,
                           record=args.save_video, train_state_seed=0)
        if args.use_mujoco:
            algo_cls.play_policy_mujoco(env, agent_conf, agent_state, **play_kwargs)
        else:
            algo_cls.play_policy(env, agent_conf, agent_state, n_envs=1, **play_kwargs)
        log("demo finished (checkpoint replay).", log_file)
        log(f"log_file: {log_path}", log_file)
        return

    # Random-action path — plain env + action_space.sample()
    from loco_mujoco import RLFactory, ImitationFactory
    factory_cls = RLFactory if args.task_factory == "RLFactory" else ImitationFactory
    env = factory_cls.make(args.env_name)
    log(f"built env: {args.task_factory}.make('{args.env_name}')", log_file)

    try:
        env.reset(seed=args.seed)
    except TypeError:
        env.reset()

    try:
        total_reward = 0.0
        frames = []
        action_shape = env.info.action_space.shape
        for i in range(args.n_steps):
            action = np.random.uniform(-1.0, 1.0, action_shape).astype(np.float32)
            step_out = env.step(action)
            if len(step_out) == 5:
                obs, reward, terminated, truncated, info = step_out
                done = bool(terminated) or bool(truncated)
            else:
                obs, reward, done, info = step_out
            total_reward += float(reward) if reward is not None else 0.0

            if args.save_video:
                try:
                    frame = env.render(mode="rgb_array") if args.gui else None
                except Exception:
                    frame = None
                if frame is not None:
                    frames.append(np.asarray(frame, dtype=np.uint8))
            log(f"step {i}: reward={reward} done={done}", log_file)
            if args.gui:
                try:
                    env.render()
                except Exception as e:
                    log(f"[warn] render failed: {e}", log_file)
                    args.gui = False
            if done:
                break

        log("", log_file)
        log(f"demo finished: {i+1} steps, total_reward={total_reward:.3f}", log_file)
        if args.save_video and frames:
            try:
                import imageio
                mp4 = os.path.join(run_dir, "demo.mp4")
                writer = imageio.get_writer(
                    mp4, fps=args.video_fps, format="FFMPEG", codec="libx264")
                for f in frames:
                    writer.append_data(f)
                writer.close()
                log(f"saved video: {mp4}", log_file)
            except Exception as e:
                log(f"[warn] imageio write failed: {type(e).__name__}: {e}", log_file)
        log(f"log_file: {log_path}", log_file)
    finally:
        if not log_file.closed:
            log_file.close()


if __name__ == "__main__":
    main()
