"""
loco-mujoco RL training dispatcher. Selects an algorithm via --algo and delegates
to the repo's own training entrypoint under examples/training_examples/<algo>/experiment.py.

Generated by benchmark-env-generator (RL Category, dispatcher mode — repo ships its
own baselines). Hydra-driven: pass Hydra overrides as positional args after --algo.

Example:
    python scripts/train_rl_policy.py --algo ppo experiment.total_timesteps=5000
"""
import argparse
import subprocess
import sys
from pathlib import Path

# Filled from probe results: repo has examples/training_examples/{jax_rl,jax_gail,jax_amp,jax_rl_mimic}/experiment.py
ALGO_MAP: dict = {
    "ppo": "examples/training_examples/jax_rl/experiment.py",
    "gail": "examples/training_examples/jax_gail/experiment.py",
    "amp": "examples/training_examples/jax_amp/experiment.py",
    "rl_mimic": "examples/training_examples/jax_rl_mimic/experiment.py",
}


def _repo_root() -> Path:
    # `/workspace` in the container; fall back to script-relative when run on host.
    if Path("/workspace/pyproject.toml").is_file():
        return Path("/workspace")
    return Path(__file__).resolve().parents[1]


def main():
    parser = argparse.ArgumentParser(
        description="RL training dispatcher for loco-mujoco.",
        usage="python scripts/train_rl_policy.py --algo <name> [hydra_overrides...]",
    )
    parser.add_argument("--algo", choices=list(ALGO_MAP.keys()), help="Algorithm selector")
    parser.add_argument("--list-algos", action="store_true", help="List supported algos and exit")
    args, hydra_overrides = parser.parse_known_args()

    if args.list_algos:
        for name, path in ALGO_MAP.items():
            print(f"  {name:<12} -> {path}")
        return

    if args.algo is None:
        parser.error("--algo is required (unless --list-algos)")

    entry = _repo_root() / ALGO_MAP[args.algo]
    if not entry.is_file():
        print(f"[error] Algorithm entrypoint not found: {entry}", file=sys.stderr)
        print("        Either the upstream repo moved the training example, or the skill's "
              "ALGO_MAP is stale. Edit ALGO_MAP in this file.", file=sys.stderr)
        sys.exit(2)

    cmd = [sys.executable, str(entry), *hydra_overrides]
    print(f"[dispatch] {' '.join(cmd)}", flush=True)
    result = subprocess.run(cmd, cwd=str(_repo_root()))
    sys.exit(result.returncode)


if __name__ == "__main__":
    main()
